version: 2.1

executors:
  docker-executor:
    docker:
    - image: circleci/node:10-stretch
    working_directory: ~/trudesk-docker

commands:
  pullsubmodules:
    steps:
    - run:
        name: "Pull Submodules"
        command: |
            git submodule init
            git submodule update --remote

jobs:
  build_docker_arm:
    docker:
    - image: ubuntu:18.04
    working_directory: ~/trudesk-docker
    steps:
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Install Deps
        command: |
          apt-get update
          apt-get install -y git curl wget
    - checkout
    - pullsubmodules
    - run:
        name: Install Docker
        command: curl -fsSL https://get.docker.com/ | sh
    - run:
        name: Setup QEmu
        command: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
          wget http://trudesk.io/install/qemu-arm-static
          chmod +x qemu-arm-static
    - run:
        name: Build Docker - ARM
        command: docker build -f trudesk/Dockerfile.rp3 -t polonel/trudesk:latest-arm trudesk/
  build_docker_next:
    executor: docker-executor
    steps:
    - checkout
    - pullsubmodules
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Build Docker Image
        command: |
          docker build -t polonel/trudesk:next trudesk/
          docker tag polonel/trudesk:next polonel/trudesk:latest
    - run:
        name: Push Docker Image
        command: |
          echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
          docker push polonel/trudesk:next
          docker push polonel/trudesk:latest
  build_production_docker:
    executor: docker-executor
    steps:
    - run:
        name: Setup Environment Variables
        command: |
          wget http://trudesk.io/tools/semver
          chmod +x semver
          ~/trudesk-docker/semver get major $CIRCLE_TAG >> ~/major
          ~/trudesk-docker/semver get minor $CIRCLE_TAG >> ~/minor
          ~/trudesk-docker/semver get patch $CIRCLE_TAG >> ~/patch
          echo 'export MAJOR=$(cat ~/major)' >> $BASH_ENV
          echo 'export MINOR=$(cat ~/minor)' >> $BASH_ENV
          echo 'export PATCH=$(cat ~/patch)' >> $BASH_ENV
          rm -rf ~/trudesk-docker/*
    - checkout
    - pullsubmodules
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Build Docker Image
        command: docker build -t polonel/trudesk:latest trudesk/
    - run:
        name: Tag Docker Images
        command: |
          docker tag polonel/trudesk:latest polonel/trudesk:$MAJOR
          docker tag polonel/trudesk:latest polonel/trudesk:$(echo "${MAJOR}.${MINOR}")
          docker tag polonel/trudesk:latest polonel/trudesk:$(echo "${MAJOR}.${MINOR}.${PATCH}")
          docker images
    - run:
        name: Push Docker Image
        command: |
          echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
          docker push polonel/trudesk:latest
          docker push polonel/trudesk:$MAJOR
          docker push polonel/trudesk:$(echo "${MAJOR}.${MINOR}")
          docker push polonel/trudesk:$(echo "${MAJOR}.${MINOR}.${PATCH}")

workflows:
  version: 2.1
  docker_build:
    jobs:
    - build_docker_next:
        filters:
          branches:
            only:
            - master
    - build_docker_arm:
        filters:
          branches:
            only: dockerarm
  docker_prod:
    jobs:
    - build_production_docker:
        filters:
          tags:
            only: /^v.*/